pipeline {
    agent any

    environment {
        ENV_FILE = credentials('env_file')
        JITSI_PK = credentials('jitsi_pk')
    }

    options {
        skipDefaultCheckout()
    }

    stages {
        stage('Checkout') {
            steps {
                cleanWs()
                checkout scm: [
                    $class: 'GitSCM',
                    branches: scm.branches,
                    extensions: [[
                        $class: 'SubmoduleOption',
                        recursiveSubmodules: true,
                        parentCredentials: true,
                        trackingSubmodules: false
                    ]],
                    userRemoteConfigs: scm.userRemoteConfigs
                ]
            }
        }

        stage('Sync to deploy dir') {
            steps {
                sh 'cp $ENV_FILE .env'
                sh 'cp $JITSI_PK jitsi.pk'
                sh 'docker buildx create --name osship-buildx --config buildkit.toml || true'
                sh 'docker buildx use osship-buildx'
                sh 'docker buildx inspect --bootstrap'
                sh 'make swagger'
            }
        }

        stage('Build') {
            steps {
                sh '''
                    make build
                '''
            }
        }

        stage('Docker recreate and up') {
            steps {
                sh '''
                    make recreate
                '''
            }
        }

        stage('Migrate') {
            steps {
                sh '''
                    make migrate
                '''
            }
        }

    }

    post {
        failure {
            echo 'Pipeline failed.'
        }
        success {
            echo 'Deploy success'
        }
    }
}
