pipeline {
    agent any

    environment {
        ENV_FILE = credentials('env_file')
        JITSI_PK = credentials('jitsi_pk')
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm: [
                    $class: 'GitSCM',
                    branches: scm.branches,
                    extensions: [[
                        $class: 'SubmoduleOption',
                        recursiveSubmodules: true,
                        parentCredentials: true,
                        trackingSubmodules: false
                    ]],
                    userRemoteConfigs: scm.userRemoteConfigs
                ]
            }
        }

        stage('Sync to deploy dir') {
            steps {
                sh 'cp $ENV_FILE .env'
                sh 'cp $JITSI_PK jitsi.pk'

                sh 'ls -la'
            }
        }

        stage('Build') {
            steps {
                sh '''
                    make build
                '''
            }
        }

        stage('Migrate') {
            steps {
                sh '''
                    make migrate
                '''
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                    make up
                    docker image prune -f
                '''
            }
        }

        stage('Health check') {
            steps {
                sh '''
                    sleep 10
                    make health
                '''
            }
        }
    }

    post {
        failure {
            echo 'Pipeline failed.'
        }
        success {
            echo 'Deploy success'
        }
    }
}
